name: dependabot

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  get_current_info:
    runs-on: ubuntu-latest
    outputs:
      pkg_source_version: ${{ steps.info.outputs.pkg_source_version }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v6
        with:
          repository: MinimaxFlora/luci-app-mihomo
          ref: master
          path: luci-app-mihomo
      - id: info
        name: info
        run: |
          echo "pkg_source_version=$(grep "PKG_SOURCE_VERSION:=" luci-app-mihomo/mihomo/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
  get_latest_info:
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.info.outputs.latest_tag }}
      latest_version: ${{ steps.info.outputs.latest_version }}
      checksum: ${{ steps.info.outputs.checksum }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v6
        with:
          repository: 'MetaCubeX/mihomo'
          ref: 'Meta'
          path: 'mihomo'
          fetch-tags: true
      - id: info
        name: info
        run: |
          umask 0022
          latest_tag=$(git -C mihomo tag --sort=-v:refname | head -n 1)
          latest_version=${latest_tag#v}
          git -C mihomo checkout "$latest_tag"
          commit_timestamp=$(git -C mihomo log -n 1 --format=%cd --date=format:%s)
          pkg_name="mihomo"
          pkg_source_dir="${pkg_name}-${latest_version}"
          pkg_source="${pkg_source_dir}.tar.gz"
          mkdir -p "${pkg_source_dir}"
          git -C mihomo archive --format=tar HEAD | tar -x -f - -C "${pkg_source_dir}"
          tar --numeric-owner --owner=0 --group=0 --mode=a-s --sort=name --mtime="@${commit_timestamp}" -c "${pkg_source_dir}" | gzip -n -c > "${pkg_source}"
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "latest_version=$latest_version" >> $GITHUB_OUTPUT
          echo "checksum=$(sha256sum ${pkg_source} | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
  update:
    needs:
      - get_current_info
      - get_latest_info
    if: ${{ needs.get_current_info.outputs.pkg_source_version != needs.get_latest_info.outputs.latest_tag }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v6
        with:
          repository: MinimaxFlora/luci-app-mihomo
          ref: master
          path: luci-app-mihomo
      - id: update
        name: update
        run: |
          sed -i "s/PKG_VERSION:=.*/PKG_VERSION:=${{ needs.get_latest_info.outputs.latest_version }}/" luci-app-mihomo/mihomo/Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${{ needs.get_latest_info.outputs.latest_tag }}/" luci-app-mihomo/mihomo/Makefile
          sed -i "s/PKG_BUILD_VERSION:=.*/PKG_BUILD_VERSION:=${{ needs.get_latest_info.outputs.latest_tag }}/" luci-app-mihomo/mihomo/Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.get_latest_info.outputs.checksum }}/" luci-app-mihomo/mihomo/Makefile
      - id: pr
        name: pr
        uses: peter-evans/create-pull-request@v8
        with:
          path: luci-app-mihomo
          branch: dependabot/mihomo
          commit-message: "chore: update mihomo to ${{ needs.get_latest_info.outputs.latest_tag }}"
          title: "chore: update mihomo to ${{ needs.get_latest_info.outputs.latest_tag }}"
          body: |
            [Changelog](https://github.com/MetaCubeX/mihomo/compare/${{ needs.get_current_info.outputs.pkg_source_version }}...${{ needs.get_latest_info.outputs.latest_tag }})
